language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

install:
  # Install conan
  - pip install --user conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

before_script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake ..

script: make && make test